{{- if .Values.admissionWebhook.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "hmc.webhook.certName" . }}
spec:
  dnsNames:
    - {{ include "hmc.webhook.serviceName" . }}.{{ .Release.Namespace }}.svc
    - {{ include "hmc.webhook.serviceName" . }}.{{ .Release.Namespace }}.svc.{{ .Values.kubernetesClusterDomain }}
  issuerRef:
    kind: Issuer
    name: {{ include "hmc.fullname" . }}-selfsigned-issuer
  secretName: {{ include "hmc.webhook.certName" . }}
{{- end }}
