apiVersion: v1
kind: Service
metadata:
  name: {{ include "hmc.fullname" . }}-controller-manager-metrics-service
  labels:
    control-plane: {{ include "hmc.fullname" . }}-controller-manager
  {{- include "hmc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    control-plane: {{ include "hmc.fullname" . }}-controller-manager
  {{- include "hmc.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.metricsService.ports | toYaml | nindent 2 }}
