site_name: HMC
site_author: Mirantis
docs_dir: ./docs
repo_name: GitHub
repo_url: https://github.com/mirantis/hmc
copyright:
  '© 2005 - 2024 Mirantis, Inc. All rights reserved. “Mirantis” and “FUEL” are registered trademarks of Mirantis, Inc. All other trademarks are the property of their respective owners.'
nav:
  - Home: index.md
  - Introduction: introduction.md
  - Quick Start: quick-start.md
  - Developer Guide: dev.md



theme:
  name: "material"
  font:
    text: overpass
    code: Roboto Mono
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  icon: assets/mirantis-logo-inverted-horizontal-one-color.svg
  logo: assets/mirantis-logo-inverted-horizontal-one-color.svg
  favicon: assets/favicon.ico

  search: true
  search_index_only: true
  features:
    - toc.autohide
    - search.suggest
    - search.highlight

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - mermaid2

