apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSManagedCluster
metadata:
  name: {{ include "cluster.name" . }}
  annotations:
    aws.cluster.x-k8s.io/external-resource-gc: "true"
spec: {}
