apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "hmc.fullname" . }}-clustertemplatechains-creator-role
  labels:
    hmc.mirantis.com/aggregate-to-namespace-admin: "true"
rules:
  - apiGroups:
      - hmc.mirantis.com
    resources:
      - clustertemplatechains
    verbs: {{ include "rbac.viewerVerbs" . | nindent 6 }}
      - create
      - delete
  - apiGroups:
      - hmc.mirantis.com
    resources:
      - clustertemplates
    verbs: {{ include "rbac.viewerVerbs" . | nindent 6 }}
