apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "hmc.fullname" . }}-global-admin-role
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        hmc.mirantis.com/aggregate-to-global-admin: "true"
    - matchLabels:
        hmc.mirantis.com/aggregate-to-namespace-editor: "true"
    - matchLabels:
        hmc.mirantis.com/aggregate-to-namespace-admin: "true"
