apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "hmc.fullname" . }}-manager-rolebinding
  labels:
  {{- include "hmc.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "hmc.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "hmc.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "hmc.fullname" . }}-manager-secrets-reader-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "hmc.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ include "hmc.fullname" . }}-manager-secrets-reader-role'
subjects:
  - kind: ServiceAccount
    name: '{{ include "hmc.fullname" . }}-controller-manager'
    namespace: '{{ .Release.Namespace }}'
