image:
  repository: localhost/hmc/controller
  tag: latest
controller:
  defaultRegistryURL: oci://hmc-local-registry:5000/charts
  insecureRegistry: true
  createRelease: false
  createTemplates: false
