apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureCluster
metadata:
  name: {{ include "cluster.name" . }}
spec:
  {{- with .Values.clusterIdentity }}
  identityRef:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  location: {{ .Values.location }}
  {{- if .Values.bastion.enabled }}
  {{- with .Values.bastion.bastionSpec }}
  bastionSpec:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  subscriptionID: {{ .Values.subscriptionID }}
